#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Dec 25, 2024 03:00:00 AM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import PINNDemonstrationApp_support

_bgcolor = 'SystemButtonFace'
_fgcolor = 'SystemWindowText'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: PINNDemonstrationApp_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'vista.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('vista')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class mainWnd:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("800x600+493+327")
        top.minsize(120, 1)
        top.maxsize(1000, 800)
        top.resizable(1,  1)
        top.title("PINN Demonstration")
        top.configure(borderwidth="5")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

        self.menubar = tk.Menu(top, font="TkMenuFont", bg='SystemButtonFace'
                ,fg=_fgcolor)
        top.configure(menu = self.menubar)

        _style_code()
        self.frmInfo = ttk.Frame(self.top)
        self.frmInfo.place(relx=0.55, rely=0.1, relheight=0.8, relwidth=0.4)
        self.frmInfo.configure(relief='groove')
        self.frmInfo.configure(borderwidth="2")
        self.frmInfo.configure(relief="groove")

        self.txtProgramInfo = tk.Text(self.frmInfo)
        self.txtProgramInfo.place(relx=0.0, rely=0.0, relheight=1.0
                , relwidth=1.0)
        self.txtProgramInfo.configure(background="#b5ba87")
        self.txtProgramInfo.configure(cursor="target")
        self.txtProgramInfo.configure(font="-family {Libertinus Serif} -size 12")
        self.txtProgramInfo.configure(highlightcolor="SystemWindowText")
        self.txtProgramInfo.configure(selectbackground="#d9d9d9")
        self.txtProgramInfo.configure(selectforeground="black")
        self.txtProgramInfo.configure(state='disabled')
        self.txtProgramInfo.configure(wrap="word")
        try:
            with open("info.txt", "r", encoding="utf-8") as file:
                info_content = file.read()
                self.txtProgramInfo.configure(state='normal')
                self.txtProgramInfo.insert("1.0", info_content)
                self.txtProgramInfo.configure(state='disabled')
        except Exception as e:
            self.txtProgramInfo.configure(state='normal')
            self.txtProgramInfo.insert("1.0", "Произошла ошибка чтения файла инструкций")
            self.txtProgramInfo.configure(state='disabled')

        self.Problems = ttk.Frame(self.top)
        self.Problems.place(relx=0.1, rely=0.1, relheight=0.8, relwidth=0.4)
        self.Problems.configure(relief='groove')
        self.Problems.configure(borderwidth="2")
        self.Problems.configure(relief="groove")

        self.btnProblem2 = ttk.Button(self.Problems)
        self.btnProblem2.place(relx=0.1, rely=0.4, height=96, width=256)
        self.btnProblem2.configure(command=PINNDemonstrationApp_support.go_to_problem2)
        self.btnProblem2.configure(text='''Problem 2''')
        self.btnProblem2.configure(compound='left')

        self.btnExit = ttk.Button(self.Problems)
        self.btnExit.place(relx=0.1, rely=0.7, height=96, width=256)
        self.btnExit.configure(command=PINNDemonstrationApp_support.exit_event)
        self.btnExit.configure(text='''Exit''')
        self.btnExit.configure(compound='left')

        self.btnProblem1 = ttk.Button(self.Problems)
        self.btnProblem1.place(relx=0.1, rely=0.1, height=96, width=256)
        self.btnProblem1.configure(command=PINNDemonstrationApp_support.go_to_problem1)
        self.btnProblem1.configure(text='''Problem1''')
        self.btnProblem1.configure(compound='left')

class Problem1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1323x689+141+166")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("PINN для 1-мерной начально-кравеой задачи")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

        _style_code()
        self.presentation_frame_1 = ttk.Frame(self.top)
        self.presentation_frame_1.place(relx=0.475, rely=0.049, relheight=0.901
                , relwidth=0.5)
        self.presentation_frame_1.configure(relief='groove')
        self.presentation_frame_1.configure(borderwidth="2")
        self.presentation_frame_1.configure(relief="groove")

        self.canvas_1 = tk.Canvas(self.presentation_frame_1)
        self.canvas_1.place(relx=0.011, rely=0.056, relheight=0.449
                , relwidth=0.979)
        self.canvas_1.configure(borderwidth="2")
        self.canvas_1.configure(highlightcolor="SystemWindowText")
        self.canvas_1.configure(insertbackground="SystemWindowText")
        self.canvas_1.configure(relief="ridge")
        self.canvas_1.configure(selectbackground="#d9d9d9")
        self.canvas_1.configure(selectforeground="black")

        self.list_report_1 = tk.Listbox(self.presentation_frame_1)
        self.list_report_1.place(relx=0.011, rely=0.591, relheight=0.399
                , relwidth=0.979)
        self.list_report_1.configure(background="SystemButtonFace")
        self.list_report_1.configure(disabledforeground="#b4b4b4")
        self.list_report_1.configure(font="TkFixedFont")
        self.list_report_1.configure(foreground="SystemWindowText")
        self.list_report_1.configure(highlightcolor="SystemWindowText")
        self.list_report_1.configure(selectbackground="#d9d9d9")
        self.list_report_1.configure(selectforeground="black")

        self.canvas_1_label = ttk.Label(self.presentation_frame_1)
        self.canvas_1_label.place(relx=0.011, rely=0.01, height=31, width=595)
        self.canvas_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.canvas_1_label.configure(relief="flat")
        self.canvas_1_label.configure(anchor='w')
        self.canvas_1_label.configure(justify='left')
        self.canvas_1_label.configure(text='''Графики решения и обучения:''')
        self.canvas_1_label.configure(compound='left')

        self.info_report_1_label = ttk.Label(self.presentation_frame_1)
        self.info_report_1_label.place(relx=0.0, rely=0.536, height=32
                , width=596)
        self.info_report_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.info_report_1_label.configure(relief="flat")
        self.info_report_1_label.configure(anchor='w')
        self.info_report_1_label.configure(justify='left')
        self.info_report_1_label.configure(text='''Отчет о модели:''')
        self.info_report_1_label.configure(compound='left')

        self.control_elements_1 = ttk.Frame(self.top)
        self.control_elements_1.place(relx=0.05, rely=0.824, relheight=0.151
                , relwidth=0.4)
        self.control_elements_1.configure(relief='groove')
        self.control_elements_1.configure(borderwidth="2")
        self.control_elements_1.configure(relief="groove")

        self.create_1_btn = ttk.Button(self.control_elements_1)
        self.create_1_btn.place(relx=0.049, rely=0.058, height=83, width=212)
        self.create_1_btn.configure(command=PINNDemonstrationApp_support.create_model_1)
        self.create_1_btn.configure(text='''Создать модель''')
        self.create_1_btn.configure(compound='left')

        self.train_1_btn = ttk.Button(self.control_elements_1)
        self.train_1_btn.place(relx=0.55, rely=0.058, height=83, width=212)
        self.train_1_btn.configure(command=PINNDemonstrationApp_support.train_model_1)
        self.train_1_btn.configure(text='''Тренировать модель''')
        self.train_1_btn.configure(compound='left')

        self.input_container_1 = ttk.Frame(self.top)
        self.input_container_1.place(relx=0.05, rely=0.049, relheight=0.75
                , relwidth=0.4)
        self.input_container_1.configure(relief='groove')
        self.input_container_1.configure(borderwidth="2")
        self.input_container_1.configure(relief="groove")

        self.k_1_input = ttk.Entry(self.input_container_1)
        self.k_1_input.place(relx=0.2, rely=0.101, relheight=0.05
                , relwidth=0.699)
        self.k_1_input.configure(font="-family {Segoe UI} -size 9")
        self.k_1_input.configure(cursor="ibeam")

        self.q_1_input = ttk.Entry(self.input_container_1)
        self.q_1_input.place(relx=0.2, rely=0.199, relheight=0.05
                , relwidth=0.699)
        self.q_1_input.configure(font="-family {Segoe UI} -size 9")
        self.q_1_input.configure(cursor="ibeam")

        self.f_1_input = ttk.Entry(self.input_container_1)
        self.f_1_input.place(relx=0.2, rely=0.3, relheight=0.05, relwidth=0.699)
        self.f_1_input.configure(font="-family {Segoe UI} -size 9")
        self.f_1_input.configure(cursor="ibeam")

        self.a_1_input = ttk.Entry(self.input_container_1)
        self.a_1_input.place(relx=0.2, rely=0.4, relheight=0.05, relwidth=0.301)
        self.a_1_input.configure(font="-family {Segoe UI} -size 9")
        self.a_1_input.configure(cursor="ibeam")

        self.b_1_input = ttk.Entry(self.input_container_1)
        self.b_1_input.place(relx=0.599, rely=0.4, relheight=0.05
                , relwidth=0.301)
        self.b_1_input.configure(font="-family {Segoe UI} -size 9")
        self.b_1_input.configure(cursor="ibeam")

        self.u_a_1_input = ttk.Entry(self.input_container_1)
        self.u_a_1_input.place(relx=0.2, rely=0.501, relheight=0.048
                , relwidth=0.301)
        self.u_a_1_input.configure(font="-family {Segoe UI} -size 9")
        self.u_a_1_input.configure(cursor="ibeam")

        self.u_b_1_input = ttk.Entry(self.input_container_1)
        self.u_b_1_input.place(relx=0.599, rely=0.501, relheight=0.048
                , relwidth=0.301)
        self.u_b_1_input.configure(font="-family {Segoe UI} -size 9")
        self.u_b_1_input.configure(cursor="ibeam")

        self.interval_1_info = ttk.Label(self.input_container_1)
        self.interval_1_info.place(relx=0.75, rely=0.801, height=26, width=106)
        self.interval_1_info.configure(font="-family {Libertinus Serif} -size 9 -weight bold")
        self.interval_1_info.configure(relief="flat")
        self.interval_1_info.configure(anchor='w')
        self.interval_1_info.configure(justify='left')
        self.interval_1_info.configure(text='''100''')
        self.interval_1_info.configure(compound='left')

        self.batch_size_1_info = ttk.Label(self.input_container_1)
        self.batch_size_1_info.place(relx=0.75, rely=0.689, height=27, width=106)

        self.batch_size_1_info.configure(font="-family {Libertinus Serif} -size 9 -weight bold")
        self.batch_size_1_info.configure(relief="flat")
        self.batch_size_1_info.configure(anchor='w')
        self.batch_size_1_info.configure(justify='left')
        self.batch_size_1_info.configure(text='''32''')
        self.batch_size_1_info.configure(compound='left')

        self.epochs_1_info = ttk.Label(self.input_container_1)
        self.epochs_1_info.place(relx=0.75, rely=0.6, height=27, width=106)
        self.epochs_1_info.configure(font="-family {Libertinus Serif} -size 9 -weight bold")
        self.epochs_1_info.configure(relief="flat")
        self.epochs_1_info.configure(anchor='w')
        self.epochs_1_info.configure(justify='left')
        self.epochs_1_info.configure(text='''1000''')
        self.epochs_1_info.configure(compound='left')

        self.info_int_1_scale = ttk.Scale(self.input_container_1, from_=100, to=10000)
        self.info_int_1_scale.place(relx=0.2, rely=0.801, relheight=0.048
                , relwidth=0.499)
        self.info_int_1_scale.configure(command=PINNDemonstrationApp_support.interval_1_chng)

        self.k_1_label = ttk.Label(self.input_container_1)
        self.k_1_label.place(relx=0.049, rely=0.101, height=26, width=53)
        self.k_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.k_1_label.configure(relief="flat")
        self.k_1_label.configure(anchor='w')
        self.k_1_label.configure(justify='left')
        self.k_1_label.configure(text='''k:''')
        self.k_1_label.configure(compound='left')

        self.q_1_label = ttk.Label(self.input_container_1)
        self.q_1_label.place(relx=0.062, rely=0.199, height=27, width=53)
        self.q_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.q_1_label.configure(relief="flat")
        self.q_1_label.configure(anchor='w')
        self.q_1_label.configure(justify='left')
        self.q_1_label.configure(text='''q:''')
        self.q_1_label.configure(compound='left')

        self.f_1_label = ttk.Label(self.input_container_1)
        self.f_1_label.place(relx=0.062, rely=0.311, height=26, width=53)
        self.f_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.f_1_label.configure(relief="flat")
        self.f_1_label.configure(anchor='w')
        self.f_1_label.configure(justify='left')
        self.f_1_label.configure(text='''f:''')
        self.f_1_label.configure(compound='left')

        self.a_b_1_label = ttk.Label(self.input_container_1)
        self.a_b_1_label.place(relx=0.049, rely=0.4, height=26, width=53)
        self.a_b_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.a_b_1_label.configure(relief="flat")
        self.a_b_1_label.configure(anchor='w')
        self.a_b_1_label.configure(justify='left')
        self.a_b_1_label.configure(text='''a, b:''')
        self.a_b_1_label.configure(compound='left')

        self.u_a_u_b_1_label = ttk.Label(self.input_container_1)
        self.u_a_u_b_1_label.place(relx=0.049, rely=0.501, height=26, width=80)
        self.u_a_u_b_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.u_a_u_b_1_label.configure(relief="flat")
        self.u_a_u_b_1_label.configure(anchor='w')
        self.u_a_u_b_1_label.configure(justify='left')
        self.u_a_u_b_1_label.configure(text='''u_a,u_b:''')
        self.u_a_u_b_1_label.configure(compound='left')

        self.batch_size_1_label = ttk.Label(self.input_container_1)
        self.batch_size_1_label.place(relx=0.019, rely=0.7, height=26, width=96)
        self.batch_size_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.batch_size_1_label.configure(relief="flat")
        self.batch_size_1_label.configure(anchor='w')
        self.batch_size_1_label.configure(justify='left')
        self.batch_size_1_label.configure(text='''batch size:''')
        self.batch_size_1_label.configure(compound='left')

        self.info_1_label = ttk.Label(self.input_container_1)
        self.info_1_label.place(relx=0.019, rely=0.801, height=26, width=96)
        self.info_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.info_1_label.configure(relief="flat")
        self.info_1_label.configure(anchor='w')
        self.info_1_label.configure(justify='left')
        self.info_1_label.configure(text='''interval:''')
        self.info_1_label.configure(compound='left')

        self.epochs_1_label = ttk.Label(self.input_container_1)
        self.epochs_1_label.place(relx=0.049, rely=0.6, height=27, width=63)
        self.epochs_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.epochs_1_label.configure(relief="flat")
        self.epochs_1_label.configure(anchor='w')
        self.epochs_1_label.configure(justify='left')
        self.epochs_1_label.configure(text='''epocsh:''')
        self.epochs_1_label.configure(compound='left')

        self.epochs_1_scale = ttk.Scale(self.input_container_1, from_=1000, to=100000)
        self.epochs_1_scale.place(relx=0.2, rely=0.6, relheight=0.05
                , relwidth=0.501)
        self.epochs_1_scale.configure(command=PINNDemonstrationApp_support.epochs_1_chng)

        self.batch_size_1_scale = ttk.Scale(self.input_container_1, from_=32, to=256)
        self.batch_size_1_scale.place(relx=0.2, rely=0.7, relheight=0.05
                , relwidth=0.499)
        self.batch_size_1_scale.configure(command=PINNDemonstrationApp_support.batch_size_1_cnhg)

class Problem2:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1094x573+379+98")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("PINN для 2-мерной начально-краевой задачи")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

        _style_code()
        self.control_elements_2 = ttk.Frame(self.top)
        self.control_elements_2.place(relx=0.05, rely=0.775, relheight=0.201
                , relwidth=0.399)
        self.control_elements_2.configure(relief='groove')
        self.control_elements_2.configure(borderwidth="2")
        self.control_elements_2.configure(relief="groove")

        self.create_2_btn = ttk.Button(self.control_elements_2)
        self.create_2_btn.place(relx=0.05, rely=0.052, height=103, width=174)
        self.create_2_btn.configure(command=PINNDemonstrationApp_support.create_model_2)
        self.create_2_btn.configure(text='''Создать''')
        self.create_2_btn.configure(compound='left')

        self.train_2_btn = ttk.Button(self.control_elements_2)
        self.train_2_btn.place(relx=0.55, rely=0.052, height=103, width=174)
        self.train_2_btn.configure(command=PINNDemonstrationApp_support.train_model_2)
        self.train_2_btn.configure(text='''Тренировать''')
        self.train_2_btn.configure(compound='left')

        self.input_container_2 = ttk.Frame(self.top)
        self.input_container_2.place(relx=0.05, rely=0.051, relheight=0.7
                , relwidth=0.399)
        self.input_container_2.configure(relief='groove')
        self.input_container_2.configure(borderwidth="2")
        self.input_container_2.configure(relief="groove")

        self.v_1_label = ttk.Label(self.input_container_2)
        self.v_1_label.place(relx=0.05, rely=0.15, height=20, width=43)
        self.v_1_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.v_1_label.configure(relief="flat")
        self.v_1_label.configure(anchor='w')
        self.v_1_label.configure(justify='left')
        self.v_1_label.configure(text='''v_1''')
        self.v_1_label.configure(compound='left')

        self.g_2_label = ttk.Label(self.input_container_2)
        self.g_2_label.place(relx=0.05, rely=0.35, height=20, width=43)
        self.g_2_label.configure(font="-family {Liberation Serif} -size 12 -weight bold")
        self.g_2_label.configure(relief="flat")
        self.g_2_label.configure(anchor='w')
        self.g_2_label.configure(justify='left')
        self.g_2_label.configure(text='''g(a,b):''')
        self.g_2_label.configure(compound='left')

        self.a_b_2_label = ttk.Label(self.input_container_2)
        self.a_b_2_label.place(relx=0.05, rely=0.449, height=20, width=43)
        self.a_b_2_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.a_b_2_label.configure(relief="flat")
        self.a_b_2_label.configure(anchor='w')
        self.a_b_2_label.configure(justify='left')
        self.a_b_2_label.configure(text='''a,b:''')
        self.a_b_2_label.configure(compound='left')

        self.epochs_2_label = ttk.Label(self.input_container_2)
        self.epochs_2_label.place(relx=0.05, rely=0.65, height=20, width=65)
        self.epochs_2_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.epochs_2_label.configure(relief="flat")
        self.epochs_2_label.configure(anchor='w')
        self.epochs_2_label.configure(justify='left')
        self.epochs_2_label.configure(text='''epochs:''')
        self.epochs_2_label.configure(compound='left')

        self.batch_size_2_label = ttk.Label(self.input_container_2)
        self.batch_size_2_label.place(relx=0.046, rely=0.75, height=20
                , width=87)
        self.batch_size_2_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.batch_size_2_label.configure(relief="flat")
        self.batch_size_2_label.configure(anchor='w')
        self.batch_size_2_label.configure(justify='left')
        self.batch_size_2_label.configure(text='''batch size:''')
        self.batch_size_2_label.configure(compound='left')

        self.info_2_label = ttk.Label(self.input_container_2)
        self.info_2_label.place(relx=0.05, rely=0.85, height=20, width=109)
        self.info_2_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.info_2_label.configure(relief="flat")
        self.info_2_label.configure(anchor='w')
        self.info_2_label.configure(justify='left')
        self.info_2_label.configure(text='''info interval:''')
        self.info_2_label.configure(compound='left')

        self.f_2_label = ttk.Label(self.input_container_2)
        self.f_2_label.place(relx=0.069, rely=0.05, height=20, width=43)
        self.f_2_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.f_2_label.configure(relief="flat")
        self.f_2_label.configure(anchor='w')
        self.f_2_label.configure(justify='left')
        self.f_2_label.configure(text='''f:''')
        self.f_2_label.configure(compound='left')

        self.f_2_input = ttk.Entry(self.input_container_2)
        self.f_2_input.place(relx=0.2, rely=0.05, relheight=0.05, relwidth=0.7)
        self.f_2_input.configure(font="-family {Segoe UI} -size 9")
        self.f_2_input.configure(cursor="ibeam")

        self.v_1_input = ttk.Entry(self.input_container_2)
        self.v_1_input.place(relx=0.2, rely=0.15, relheight=0.05, relwidth=0.7)
        self.v_1_input.configure(font="-family {Segoe UI} -size 9")
        self.v_1_input.configure(cursor="ibeam")

        self.v_2_label = ttk.Label(self.input_container_2)
        self.v_2_label.place(relx=0.05, rely=0.249, height=20, width=43)
        self.v_2_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.v_2_label.configure(relief="flat")
        self.v_2_label.configure(anchor='w')
        self.v_2_label.configure(justify='left')
        self.v_2_label.configure(text='''v_2:''')
        self.v_2_label.configure(compound='left')

        self.v_2_input = ttk.Entry(self.input_container_2)
        self.v_2_input.place(relx=0.2, rely=0.249, relheight=0.05, relwidth=0.7)
        self.v_2_input.configure(font="-family {Segoe UI} -size 9")
        self.v_2_input.configure(cursor="ibeam")

        self.g_2_input = ttk.Entry(self.input_container_2)
        self.g_2_input.place(relx=0.2, rely=0.35, relheight=0.05, relwidth=0.3)
        self.g_2_input.configure(font="-family {Segoe UI} -size 9")
        self.g_2_input.configure(cursor="ibeam")

        self.g_22_input = ttk.Entry(self.input_container_2)
        self.g_22_input.place(relx=0.6, rely=0.35, relheight=0.05, relwidth=0.3)
        self.g_22_input.configure(font="-family {Segoe UI} -size 9")
        self.g_22_input.configure(cursor="ibeam")

        self.a_2_input = ttk.Entry(self.input_container_2)
        self.a_2_input.place(relx=0.2, rely=0.449, relheight=0.05, relwidth=0.3)
        self.a_2_input.configure(font="-family {Segoe UI} -size 9")
        self.a_2_input.configure(cursor="ibeam")

        self.b_2_input = ttk.Entry(self.input_container_2)
        self.b_2_input.place(relx=0.601, rely=0.449, relheight=0.05
                , relwidth=0.3)
        self.b_2_input.configure(font="-family {Segoe UI} -size 9")
        self.b_2_input.configure(cursor="ibeam")

        self.epochs_2_info = ttk.Label(self.input_container_2)
        self.epochs_2_info.place(relx=0.8, rely=0.65, height=20, width=65)
        self.epochs_2_info.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.epochs_2_info.configure(relief="flat")
        self.epochs_2_info.configure(anchor='w')
        self.epochs_2_info.configure(justify='left')
        self.epochs_2_info.configure(text='''1000''')
        self.epochs_2_info.configure(compound='left')

        self.batch_size_2_info = ttk.Label(self.input_container_2)
        self.batch_size_2_info.place(relx=0.8, rely=0.75, height=20, width=65)
        self.batch_size_2_info.configure(font="-family {Liberation Serif} -size 12 -weight bold")
        self.batch_size_2_info.configure(relief="flat")
        self.batch_size_2_info.configure(anchor='w')
        self.batch_size_2_info.configure(justify='left')
        self.batch_size_2_info.configure(text='''32''')
        self.batch_size_2_info.configure(compound='left')

        self.interval_2_info = ttk.Label(self.input_container_2)
        self.interval_2_info.place(relx=0.8, rely=0.85, height=20, width=65)
        self.interval_2_info.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.interval_2_info.configure(relief="flat")
        self.interval_2_info.configure(anchor='w')
        self.interval_2_info.configure(justify='left')
        self.interval_2_info.configure(text='''100''')
        self.interval_2_info.configure(compound='left')

        self.epochs_2_scale = ttk.Scale(self.input_container_2, from_=1000, to=100000.0)
        self.epochs_2_scale.place(relx=0.25, rely=0.65, relheight=0.05
                , relwidth=0.5)
        self.epochs_2_scale.configure(command=PINNDemonstrationApp_support.epochs_2_chng)

        self.batch_size_2_scale = ttk.Scale(self.input_container_2, from_=32, to=256.0)
        self.batch_size_2_scale.place(relx=0.25, rely=0.75, relheight=0.05
                , relwidth=0.5)
        self.batch_size_2_scale.configure(command=PINNDemonstrationApp_support.batch_size_2_chng)

        self.info_int_2_scale = ttk.Scale(self.input_container_2, from_=100, to=10000.0)
        self.info_int_2_scale.place(relx=0.3, rely=0.85, relheight=0.05
                , relwidth=0.45)
        self.info_int_2_scale.configure(command=PINNDemonstrationApp_support.interval_2_chng)

        self.presentation_frame_2 = ttk.Frame(self.top)
        self.presentation_frame_2.place(relx=0.5, rely=0.051, relheight=0.901
                , relwidth=0.48)
        self.presentation_frame_2.configure(relief='groove')
        self.presentation_frame_2.configure(borderwidth="2")
        self.presentation_frame_2.configure(relief="groove")

        self.list_report_2 = tk.Listbox(self.presentation_frame_2)
        self.list_report_2.place(relx=0.01, rely=0.55, relheight=0.424
                , relwidth=0.981)
        self.list_report_2.configure(background="white")
        self.list_report_2.configure(disabledforeground="#b4b4b4")
        self.list_report_2.configure(font="TkFixedFont")
        self.list_report_2.configure(foreground="SystemWindowText")
        self.list_report_2.configure(highlightcolor="SystemWindowText")
        self.list_report_2.configure(selectbackground="#d9d9d9")
        self.list_report_2.configure(selectforeground="black")

        self.canvas_2 = tk.Canvas(self.presentation_frame_2)
        self.canvas_2.place(relx=0.01, rely=0.05, relheight=0.45, relwidth=0.981)

        self.canvas_2.configure(borderwidth="2")
        self.canvas_2.configure(highlightcolor="SystemWindowText")
        self.canvas_2.configure(insertbackground="SystemWindowText")
        self.canvas_2.configure(relief="ridge")
        self.canvas_2.configure(selectbackground="#d9d9d9")
        self.canvas_2.configure(selectforeground="black")

        self.canvas_2_label = ttk.Label(self.presentation_frame_2)
        self.canvas_2_label.place(relx=0.01, rely=0.01, height=21, width=473)
        self.canvas_2_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.canvas_2_label.configure(relief="flat")
        self.canvas_2_label.configure(anchor='w')
        self.canvas_2_label.configure(justify='left')
        self.canvas_2_label.configure(text='''График решения и обучения:''')
        self.canvas_2_label.configure(compound='left')

        self.list_report_2_label = ttk.Label(self.presentation_frame_2)
        self.list_report_2_label.place(relx=0.019, rely=0.504, height=26
                , width=472)
        self.list_report_2_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.list_report_2_label.configure(relief="flat")
        self.list_report_2_label.configure(anchor='w')
        self.list_report_2_label.configure(justify='left')
        self.list_report_2_label.configure(text='''Отчет об обучении:''')
        self.list_report_2_label.configure(compound='left')

        self.c_d_2_label = ttk.Label(self.input_container_2)
        self.c_d_2_label.place(relx=0.05, rely=0.55, height=20, width=43)
        self.c_d_2_label.configure(font="-family {Libertinus Serif} -size 12 -weight bold")
        self.c_d_2_label.configure(relief="flat")
        self.c_d_2_label.configure(anchor='w')
        self.c_d_2_label.configure(justify='left')
        self.c_d_2_label.configure(text='''c,d:''')
        self.c_d_2_label.configure(compound='left')

        self.c_2_input = ttk.Entry(self.input_container_2)
        self.c_2_input.place(relx=0.2, rely=0.55, relheight=0.05, relwidth=0.3)
        self.c_2_input.configure(font="-family {Segoe UI} -size 9")
        self.c_2_input.configure(cursor="ibeam")

        self.d_2_input = ttk.Entry(self.input_container_2)
        self.d_2_input.place(relx=0.601, rely=0.55, relheight=0.05
                             , relwidth=0.3)
        self.d_2_input.configure(font="-family {Segoe UI} -size 9")
        self.d_2_input.configure(cursor="ibeam")

def start_up():
    PINNDemonstrationApp_support.main()

if __name__ == '__main__':
    PINNDemonstrationApp_support.main()




